

import RegisterForm from './RegisterForm';
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "ثبت نام",
  description: "Generated by create next app",
};

export default function Login() {
  return (
    <div className="relative w-full h-screen overflow-hidden">
      <div className="absolute inset-0 bg-gray-100 blur-lg"></div>
      <div className="relative flex justify-center items-center h-full">
        <RegisterForm />
      </div>
    </div>
  );
}
